name: omni-reporter-sbt-plugin-pull_request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Run tests
      run: sbt test

    - name: Run Build
      run: make build
